---
# handlers file for install_nginx_php-fpm
<<<<<<< HEAD
- name: Reload Nginx
  service:
       name: nginx
       state: reloaded

- name: Restart Nginx
  service:
       name: nginx
       state: restarted
=======
#- name: Reload Nginx
#  service:
#       name: nginx
#       state: reloaded

#- name: Restart Nginx
#  service:
#       name: nginx
#       state: restarted
---
- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  notify: restart php-fpm
  when: php_enable_webserver

- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: "{{ php_fpm_handler_state }}"
  when:
    - php_enable_php_fpm
    - php_fpm_state == 'started'
>>>>>>> 3e1c1a02141cee423b702fcb7b22e5391ef2b7ce
